Repository HumanExposure/factotum, pull requests merged in 2019-11, with the labels that each got.

#1171 700 automatic documentation
  bulkformsets/forms.py
  dashboard/migrations/0135_auto_20191031_1351.py
  dashboard/models/data_document.py
  dashboard/models/data_group.py
  dashboard/models/data_source.py
  dashboard/models/extracted_list_presence.py
  dashboard/views/get_data.py
  docs/Makefile
  docs/_static/.gitignore
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/modules/bulkformsets.rst
  docs/modules/dashboard/models.rst
  docs/modules/dashboard/views.rst
  docs/modules/elastic.rst
  elastic/search.py
  factotum/settings.py
  factotum/urls.py
  requirements.txt
Labels: migrate

#1170 1028 unit type null
  dashboard/forms/data_group.py
  dashboard/migrations/0136_null_blank_unit_type.py
  dashboard/models/extracted_chemical.py
  dashboard/tests/functional/test_clean_comp_data_upload.py
  dashboard/tests/functional/test_extracted_text_upload.py
  dashboard/utils.py
  docs/_build/doctrees/environment.pickle
  docs/_build/doctrees/index.doctree
  docs/_build/doctrees/modules/dashboard/models.doctree
  docs/_build/doctrees/modules/dashboard/utils.doctree
  docs/_build/html/_sources/index.rst.txt
  docs/_build/html/_sources/modules/dashboard/utils.rst.txt
  docs/_build/html/genindex.html
  docs/_build/html/index.html
  docs/_build/html/modules/dashboard/models.html
  docs/_build/html/modules/dashboard/utils.html
  docs/_build/html/objects.inv
  docs/_build/html/py-modindex.html
  docs/_build/html/search.html
  docs/_build/html/searchindex.js
  docs/index.rst
  docs/modules/dashboard/utils.rst
Labels: data migration

#1196 Unblock extracted text upload
  templates/data_group/datagroup_detail.html
Labels: hot fix

#1197 Fix script_id in template
  templates/data_group/datagroup_detail.html
Labels: hot fix

#1180 1151 full-width product detail page PLUS
  dashboard/fixtures/05_product.yaml
  dashboard/fixtures/12_product_to_puc.yaml
  dashboard/migrations/0138_field_names.py
  dashboard/models/extracted_text.py
  dashboard/tests/functional/test_product_csv_upload.py
  dashboard/tests/functional/test_product_detail.py
  dashboard/tests/functional/test_product_dup_check.py
  dashboard/tests/functional/test_product_puc.py
  dashboard/tests/functional/test_products_list.py
  dashboard/tests/integration/test_bulk_product_puc.py
  static/css/bootstrap_overrides.css
  static/css/dashboard/anchored_footer.css
  static/css/dashboard/datadocument_detail.css
  static/css/dashboard/full_width_container.css
  templates/core/base.html
  templates/data_document/data_document_detail.html
  templates/product_curation/product_detail.html
Labels: migrate
