Repository HumanExposure/factotum, pull requests merged in 2019-10, with the labels that each got.

#1102 1032 kind admin
  bulkformsets/serializers.py
  dashboard/admin.py
  dashboard/fixtures/14_list_presence_tag.yaml
  dashboard/migrations/0123_remove_parent_link.py
  dashboard/migrations/0124_doc_url_length.py
  dashboard/migrations/0125_extractedlistpresencetagkind.py
  dashboard/models/__init__.py
  dashboard/models/extracted_list_presence.py
  dashboard/tests/functional/test_datadocument_detail.py
  dashboard/tests/integration/test_browser_edits.py
  dashboard/utils.py
Labels: data migration, migrate

#1112 1031 report funcuse field length
  bulkformsets/serializers.py
  dashboard/migrations/0123_remove_parent_link.py
  dashboard/migrations/0124_doc_url_length.py
  dashboard/migrations/0125_functuse_field_len.py
  dashboard/models/extracted_chemical.py
  dashboard/models/extracted_functional_use.py
  dashboard/models/extracted_list_presence.py
  dashboard/tests/functional/test_datadocument_detail.py
  dashboard/tests/integration/test_browser_edits.py
  dashboard/utils.py
Labels: makemigration, migrate

#1111 1036 associate component with chemical
  dashboard/forms/forms.py
  dashboard/migrations/0127_extractedchemical_component.py
  dashboard/models/data_group.py
  dashboard/models/extracted_chemical.py
  dashboard/models/unit_type.py
  dashboard/tests/functional/test_datagroup_detail.py
  dashboard/tests/functional/test_extracted_text_upload.py
  templates/data_document/chemical_cards.html
  templates/forms/extracted_formset.html
  templates/forms/extracted_formset_table.html
Labels: migrate

#1115 659 validate dg
  bulkformsets/forms.py
  bulkformsets/serializers.py
  dashboard/fixtures/01_lookups.yaml
  dashboard/fixtures/06_datadocument.yaml
  dashboard/forms/data_group.py
  dashboard/forms/forms.py
  dashboard/migrations/0126_functuse_field_len.py
  dashboard/migrations/0128_remove_nulls_doc_group_type.py
  dashboard/models/data_document.py
  dashboard/models/data_group.py
  dashboard/signals.py
  dashboard/tests/functional/test_datadocument_create.py
  dashboard/tests/functional/test_datadocument_detail.py
  dashboard/tests/functional/test_datagroup_create_upload.py
  dashboard/tests/functional/test_datagroup_form.py
  dashboard/tests/functional/test_product_linkage.py
  dashboard/tests/functional/test_search.py
  dashboard/tests/integration/test_browser_edits.py
  dashboard/views/data_document.py
  dashboard/views/data_group.py
  dashboard/views/product_curation.py
  templates/data_group/datagroup_form.html
Labels: migrate

#1125 14 Django REST Framework
  MANIFEST.in
  dashboard/apps.py
  dashboard/models/data_group.py
  dashboard/models/extracted_chemical.py
  dashboard/models/raw_chem.py
  dashboard/tests/unit/test_raw_chem.py
  dashboard/utils.py
  setup.py
Labels: migrate

#1143 1128: create auditlog table and triggers to audit fields interested in
  dashboard/forms/data_group.py
  dashboard/migrations/0131_auditlog.py
  dashboard/migrations/0132_auditlog_triggers.py
  dashboard/models/__init__.py
  dashboard/models/audit_log.py
  dashboard/signals.py
  dashboard/tests/functional/test_auditlog.py
  factotum/settings.py
  requirements.txt
Labels: migrate, requirements

#1142 1105 blank chem records
  dashboard/forms/chemical_curation.py
  dashboard/forms/data_group.py
  dashboard/migrations/0134_rm_blank_chems.py
  dashboard/models/data_document.py
  dashboard/models/extracted_chemical.py
  dashboard/tests/functional/test_datadocument_detail.py
  dashboard/tests/functional/test_extracted_text_upload.py
  dashboard/utils.py
  dashboard/views/bulk_documents.py
  templates/data_group/datagroup_detail.html
Labels: data migration
